import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Container,
  Typography,
} from "@mui/material";
import { MdExpandMore } from "react-icons/md";
import "./Faq.scss";
const faqData = [
  {
    question: "What is SMS marketing automation?",
    answer:
      "Two-factor authentication (2FA) is a security process in which a user provides two different authentication factors to verify themselves. These factors can include something the user knows (like a password), something the user has (like a smartphone or hardware token), or something the user is (like a fingerprint). 2FA adds an extra layer of security, making it more difficult for unauthorized users to access an account.",
  },
  {
    question: "Can you automate SMS?",
    answer:
      "When a user attempts to log in with 2FA enabled, they are typically required to provide their password (the first factor) as well as a second factor, which could be a code sent to their mobile device, generated by an authentication app, or obtained from a hardware token. Once both factors are provided and verified, access is granted.",
  },
  {
    question: "Is SMS marketing illegal?",
    answer:
      "Two-factor authentication is important because it significantly enhances the security of online accounts and sensitive information. By requiring multiple forms of verification, even if one factor (like a password) is compromised, the account remains protected. This helps prevent unauthorized access, data breaches, and identity theft.",
  },
  {
    question: "How to do marketing through SMS?",
    answer:
      "There are several types of two-factor authentication, including SMS-based verification, app-based authentication (using authenticator apps like Google Authenticator or Authy), email-based verification, hardware tokens (physical devices that generate authentication codes), biometric authentication (using fingerprints or facial recognition), and more.",
  },
];
const Faq = () => {
  return (
    <Container className="faq-container">
      <Typography variant="h4">Frequently asked questions</Typography>
      <Box component="div" className="accordion-box" sx={{xs:{width:'100%'}}}>
        {faqData.map((faq) => (
          <Accordion className="accordion" key={faq.question}>
            <AccordionSummary
              expandIcon={<MdExpandMore className="exp-icon" />}
              aria-controls="panel1-content"
              id="panel1-header"
              className="accordion-summary"
            >
              {faq.question}
            </AccordionSummary>
            <AccordionDetails sx={{ fontSize: 20 }}>
             {faq.answer}
            </AccordionDetails>
          </Accordion>
        ))}
      </Box>
    </Container>
  );
};

export default Faq;
